In [53]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer


In [30]:
d={
    'col1':[10,20,np.nan,20,10],
    'col2':[100,200,200,np.nan,300],
    'col3':['A',np.nan,'C','A','B']
}

In [31]:
df=pd.DataFrame(d)
df

,col1,col2,col3
0,10.0,100.0,A
1,20.0,200.0,NaN
2,NaN,200.0,C
3,20.0,NaN,A
4,10.0,300.0,B


In [36]:
imputer=SimpleImputer(strategy='constant',fill_value=0)

In [40]:
imputer2=SimpleImputer(strategy='constant',fill_value='unknown values')

In [38]:
imputer.fit_transform(df[['col1','col2']])

array([[ 10., 100.],
       [ 20., 200.],
       [  0., 200.],
       [ 20.,   0.],
       [ 10., 300.]])

In [41]:
imputer2.fit_transform(df[['col3']])

array([['A'],
       ['unknown values'],
       ['C'],
       ['A'],
       ['B']], dtype=object)

In [52]:
imputer_mean=SimpleImputer(strategy='mean')
imputer_mean.fit_transform(df[['col1','col2']])
# imputer_mean.fit_transform(df[['col3']])  # ValueError: Cannot use mean strategy with non-numeric data:

array([[ 10., 100.],
       [ 20., 200.],
       [ 15., 200.],
       [ 20., 200.],
       [ 10., 300.]])

In [50]:
imputer_median=SimpleImputer(strategy='median')
imputer_median.fit_transform(df[['col1','col2']])

array([[ 10., 100.],
       [ 20., 200.],
       [ 15., 200.],
       [ 20., 200.],
       [ 10., 300.]])

In [ ]:
imputer_mode=SimpleImputer(strategy='most_frequent')
imputer_mode.fit_transform(df[['col3']])
imputer_mode.fit_transform(df[['col1']]) # i used two fit trasform only for testing in real time don't use to fit transform for tow times

array([[10.],
       [20.],
       [10.],
       [20.],
       [10.]])